recmo/uint

- Changelog.md
- src/algorithms/gcd/matrix.rs
- src/algorithms/mod.rs
- src/algorithms/mul_redc.rs
- src/algorithms/primaility.rs
- src/modular.rs
- src/mul.rs
> Add mul_redc

- src/algorithms/div/knuth.rs
- src/algorithms/div/small.rs
- src/algorithms/mod.rs
- src/algorithms/mul.rs
- src/algorithms/mul_redc.rs
- src/bytes.rs
- src/modular.rs
- src/mul.rs
```
mul/0                   time:   [314.76 ps 316.08 ps 317.58 ps]
change: [-67.015% -66.814% -66.631%] (p = 0.00 < 0.05)
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
5 (5.00%) high mild
mul/64                  time:   [1.0591 ns 1.1872 ns 1.3455 ns]
change: [-69.394% -62.392% -52.481%] (p = 0.00 < 0.05)
Performance has improved.
Found 11 outliers among 100 measurements (11.00%)
1 (1.00%) high mild
10 (10.00%) high severe
mul/128                 time:   [2.2009 ns 2.3544 ns 2.5397 ns]
change: [-74.758% -71.251% -66.321%] (p = 0.00 < 0.05)
Performance has improved.
Found 15 outliers among 100 measurements (15.00%)
1 (1.00%) low mild
3 (3.00%) high mild
11 (11.00%) high severe
mul/192                 time:   [4.4369 ns 4.6025 ns 4.7911 ns]
change: [-68.195% …
```
> Revm optim

- src/support/serde.rs
https://github.com/paradigmxyz/reth/issues/1784 highlighted that deserialization allows strings that are too long, for example `0x000` would be successfully deserialized for a single-byte `Uint`.
Ensure that the input string to deserialize is not longer than 2 times the max number of bytes.
Added tests for max value (`0xffff...`) inputs and zero value (`0x0000...`) inputs.
> fix: disallow deser for strings that are too long

- .github/workflows/audit.yml
- .github/workflows/ci.yml
Basically all of the `actions-rs/*` actions are unmaintained. See <https://github.com/actions-rs/toolchain/issues/216> for more information. Due to their age they generate several warnings in CI runs, for example in https://github.com/recmo/uint/actions/runs/4754627965:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions-rs/toolchain@v1, Swatinem/rust-cache@v1, actions-rs/cargo@v1, actions-rs/clippy-check@v1. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
To get rid of some of those warnings the occurrences of `actions-rs/toolchain` are replaced by [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain), and the occurrences of …
> Replace unmaintained actions-rs/* actions in CI workflows

- Changelog.md
- src/base_convert.rs
Closes #248 
Check after conversion that the highest limb is within the mask. This reproduces the `Self::MASK` check logic within `Uint::from_limbs`
- [n/a] Added Documentation
> fix: prevent overflowing instantiation in from_base_be

- src/base_convert.rs
`LIMBS` can be 0, which panics at runtime on subtraction overflow
> fix: `from_base_be` overflow

- Changelog.md
- src/base_convert.rs
The current implementation is the same as `from_base_be`.
Additionally, this patch can be applied to avoid allocating (ref #254), but it is a breaking change:
```diff
diff --git a/src/base_convert.rs b/src/base_convert.rs
index 9bc059f..f928e7d 100644
--- a/src/base_convert.rs
+++ b/src/base_convert.rs
@@ -64,13 +64,12 @@ impl<const BITS: usize, const LIMBS: usize> Uint<BITS, LIMBS> {
/// * [`BaseConvertError::InvalidDigit`] if a digit is out of range.
/// * [`BaseConvertError::Overflow`] if the number is too large to
/// fit.
-    pub fn from_base_le<I: IntoIterator<Item = u64>>(
-        base: u64,
-        digits: I,
-    ) -> Result<Self, BaseConvertError> {
-        let mut digits: Vec<_> = digits.into_iter().collect();
-        digits.reverse();
-        Self::from_base_be(base, …
```
> fix: `from_base_le`

- Cargo.toml
- deny.toml
- ruint-macro/Cargo.toml
- ruint-macro/README.md
- ruint-macro/tests/parse_mixed.rs
> [Note: [...] path dev-dependencies are ignored](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies
)
This should work with cargo-release
Partly reverts #268
> fix: ruint-macro doctests

- CHANGELOG.md
- Cargo.toml
- benches/benches/algorithms/gcd.rs
- ruint-macro/src/lib.rs
- src/algorithms/div/knuth.rs
- src/algorithms/div/reciprocal.rs
- src/algorithms/gcd/matrix.rs
- src/algorithms/gcd/mod.rs
- src/base_convert.rs
- src/bit_arr.rs
- src/bytes.rs
- src/from.rs
- src/lib.rs
- src/log.rs
- src/pow.rs
- src/root.rs
- src/string.rs
- src/support/arbitrary.rs
- src/support/pyo3.rs
- src/support/rlp.rs
- src/support/serde.rs
- src/utils.rs
Make `ruint` `no_std`-compatible.
Supersedes #260.
See original description in #260.
Since `core::error::Error` is unstable, we instead implement the formatting using `core::fmt` and gate `impl std::error::Error` with `#[cfg(feature = "std")]`
> feat: no_std

- src/bits.rs
- src/bytes.rs
On LE we can just index into the slice
> perf: optimize `byte` method

- .github/workflows/ci.yml
Build only step is unnecessary because we already have it in the tests CI, and also it runs the tests without a convenient way (that I know of) to only build them, so remove it.
Also it runs
> ci: don't run tests twice in coverage

- CHANGELOG.md
- Cargo.toml
- src/add.rs
- src/algorithms/mod.rs
- src/base_convert.rs
- src/bit_arr.rs
- src/bits.rs
- src/bytes.rs
- src/lib.rs
- src/modular.rs
- src/string.rs
- src/utils.rs
Closes #275
Closes #276
Feature gate certain functions to `"alloc"`, which is enabled by default through `"std"`.
Unfortunately most of these cannot be alloc-free themselves, because of limitations in the Rust const generics (e.g. generic const exprs).
> feat: alloc feature

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- src/support/scale.rs
- src/support/serde.rs
Some support features fail to compile when on "default_features = false" because they don't enable "alloc".
This wasn't caught by CI because running "--all-targets" implicitly enables "std" due to the self-dependency (ruint depends on ruint as a dev-dependency with extra features enabled).
> fix: support features

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/support/bytemuck.rs
- src/support/mod.rs
This PR implements the [`Pod` trait](https://docs.rs/bytemuck/latest/bytemuck/trait.Pod.html) on `Uint` types where the size is a multiple of 64, up to 1024. This allows `Uint` types within this range to be used in instances where a `Pod` trait bound exists.
This implementation uses a simple macro to implement the `Pod` trait on the following Uint sizes listed below.
```rust
macro_rules! impl_pod {
($(($bits:expr, $limbs:expr)),+ $(,)?) => {
$(
unsafe impl Pod for Uint<{$bits}, $limbs> {}
)+
};
}
impl_pod! {
(64, 1),
(128, 2),
(192, 3),
(256, 4),
(320, 5),
(384, 6),
(448, 7),
(512, 8),
(576, 9),
(640, 10),
(704, 11),
(768, 12),
(832, 13),
(896, 14),
(960, 15),
(1024, 16),
}
```
> Feat: Implement `Pod` trait on Uint types

- src/algorithms/mod.rs
- src/algorithms/mul.rs
- src/aliases.rs
- src/base_convert.rs
> Constant space from base conversions

- src/bits.rs
`overflowing_shr` documentation linked to `u64::overflowing_shl` instead of `u64::overflowing_shr`
> fix invalid std primitive overflowing_shr link in docs

- CHANGELOG.md
- Cargo.toml
- README.md
- ruint-macro/src/lib.rs
- src/bits.rs
- src/bytes.rs
- src/support/mod.rs
- src/support/num_traits.rs
> Impl num-traits (fixes #226)

- src/add.rs
- src/base_convert.rs
- src/bits.rs
- src/modular.rs
- src/mul.rs
`array::IntoIter` is known to have worse performance than `slice::Iter`.
Use `slice::Iter` instead of `array::IntoIter`.
This makes codegen of `U256::add` identical to LLVM native `add i256`, while slightly improves the one in `sub`.
Rest of changes are `&(\w+)\.limbs` -> `$1.as_limbs()`.
Ideally we would deny inclusion of new `array::IntoIter` calls unless explicitly allowed, but I don't know how to do this since clippy does not catch it with `disallowed-methods`.
```rust
pub extern "C" fn u256_add(a: &mut aliases::U256, b: &aliases::U256) {
*a += *b;
}
pub extern "C" fn u256_sub(a: &mut aliases::U256, b: &aliases::U256) {
*a -= *b;
}
```
<details>
<p>
```diff
diff --git a/add.before.s b/add.after.s
index 2970898..528fed6 100644
--- a/add.before.s
+++ b/add.after.s
@@ -4,25 +4,14 @@ …
```
> perf: improve add and sub performance by avoiding `array::IntoIter`

- src/add.rs
- src/bit_arr.rs
- src/bits.rs
- src/macros.rs
- src/mul.rs
It's allowed at the crate scope.
> chore: remove unnecessary `#[allow(clippy::inline_always)]`

- CHANGELOG.md
- src/aliases.rs
Successor to #303 
Add 96-byte alias
> feature: add 768 alias

- CHANGELOG.md
- src/add.rs
- src/cmp.rs
By changing `for` with `while` we can make mark `add` and `sub` functions as `const`.
> feat: make add and sub const fns

- src/algorithms/mul.rs
Use slice/array patterns to simplify `addmul`.
Reduces LLVM generated which may or may not improve performance or binary size.
> chore: simplify mul

- src/algorithms/add.rs
- src/algorithms/div/knuth.rs
- src/algorithms/div/small.rs
- src/algorithms/mod.rs
- src/bits.rs
- src/bytes.rs
- src/utils.rs
- Use normal range loop where it makes sense.
- Use same impl as `Ord for [T]` for `algorithms::cmp`
> chore: loops clean up

- CHANGELOG.md
- src/bytes.rs
Const impl + some perf gains
Hand roll use of iterators, for loops and `slice::reverse`
> feat: make `{from,to}_{b,l}e_bytes` const

- src/bytes.rs
Follow up to #329
Move the specialized `from_*_bytes` impl to the lowest function
> perf: generalize specialized full-limb `from_*_bytes` impl

- CHANGELOG.md
- Cargo.toml
- ruint-macro/Cargo.toml
> release: 1.11.0

- CHANGELOG.md
- src/support/alloy_rlp.rs
- src/support/fastrlp.rs
Currently `Uint` RLP decoding ignores leading zeros.
Disallow leading zeros.
> fix: disallow leading zeros in RLP decoding

- CHANGELOG.md
as title -- will tag main with 1.11.0 and then release on crates
> release: roll rlp fix in 1.11.0

- CHANGELOG.md
- Cargo.toml
- deny.toml
- src/support/mod.rs
- src/support/ssz.rs
Completing SSZ implementation also for Uint types: https://github.com/alloy-rs/core/pull/407
Implementing Encode and Decode traits from https://github.com/sigp/ethereum_ssz
> feat: ssz encode and decode for uint

- src/algorithms/div/knuth.rs
- src/bit_arr.rs
- src/bytes.rs
- src/cmp.rs
- src/lib.rs
- src/mul.rs
- src/string.rs
- src/support/arbitrary.rs
- src/support/scale.rs
- src/support/serde.rs
- src/utils.rs
> chore: remove unused imports

- Cargo.toml
- ruint-macro/Cargo.toml
- ruint-macro/README.md
- ruint-macro/src/lib.rs
- src/lib.rs
- src/macros.rs
- src/support/bytemuck.rs
- src/support/serde.rs
Closes https://github.com/recmo/uint/issues/307
> feat: wrap the `uint!` macro to allow usage without needing `uint` import

- CHANGELOG.md
- src/bits.rs
`overflowing_shr` algorithm seems to give incorrect overflow results: #337.
Should close #337.
- Added code to evaluate overflow for shift operation.
- This addition enables the identification of a floating-point outcome by isolating the most significant bit of the shifted limb.
- If the least significant bit of the shifted limb is non-zero, `overflow` is set to `true`, indicating a floating-point result.
- Enhances the functionality of the `overflowing_shr` function to differentiate between floating-point and integer outcomes after the shift operation.
This enhancement improves the functionality of the `overflowing_shr` method, providing a mechanism to determine whether the result represents a floating-point or integer value.
> fix: modify `overflowing_shr` to fix overflow check

- CHANGELOG.md
- src/algorithms/div/mod.rs
- src/lib.rs
- src/macros.rs
Fixes https://github.com/recmo/uint/issues/359
> fix: allow `uint!` in item position

- CHANGELOG.md
- Cargo.toml
- src/support/num_traits.rs
I ran into the problem below when I wanted to use num-traits in a no-std (riscv64imac-unknown-none-elf) environment.
```
Compiling ruint v1.12.1
error[E0412]: cannot find type `Vec` in this scope
--> /home/xcshuan/.cargo/registry/src/github.com-1ecc6299db9ec823/ruint-1.12.1/src/support/num_traits.rs:80:18
|
80 |     type Bytes = Vec<u8>;
|                  ^^^ not found in this scope
|
help: consider importing this struct
|
7  + use alloc::vec::Vec;
|
For more information about this error, try `rustc --explain E0412`.
error: could not compile `ruint` (lib) due to 1 previous error
```
Add the following import code to `num_traits.rs`.
```
#[cfg(feature = "alloc")]
#[allow(unused_imports)]
use alloc::vec::Vec;
```
> fix num-traits with no-std

- CHANGELOG.md
- src/add.rs
- src/algorithms/div/knuth.rs
- src/bits.rs
- src/from.rs
- src/lib.rs
- src/macros.rs
Now `add`, `sub`, and `mul` have optimal codegen on x86_64.
> perf: use borrowing/carrying ops in add/sub, remove bound checks in shifts

- src/base_convert.rs
- src/bit_arr.rs
- src/cmp.rs
- src/fmt.rs
- src/lib.rs
- src/string.rs
- src/support/ark_ff_04.rs
- src/utils.rs
Improve formatting implementations by first writing to a local buffer, then using `fmt::Formatter::pad_integral` to apply padding and all the other flags.
- Closes https://github.com/recmo/uint/issues/232
- Closes https://github.com/recmo/uint/issues/295
- Closes https://github.com/recmo/uint/issues/369
This also standardizes the way the numbers are formatted to the same format that the standard library uses.
- Closes https://github.com/recmo/uint/issues/346
> feat: improve formatting implementations

- src/base_convert.rs
- src/modular.rs
Use a small hack to allocate a bit more that the required amount using nested arrays. The excess allocation only happens on uneven BITS, and should get trimmed by the optimizer anyway.
Supersedes https://github.com/recmo/uint/pull/340.
> perf: non-allocating `mul_mod`

- src/algorithms/div/mod.rs
- src/algorithms/div/reciprocal.rs
- src/algorithms/div/small.rs
- src/algorithms/mul.rs
No benefit to inlining big algorithms since they won't get optimized further and only bloat the callsite. Leave up just the inline hint rather than forcing it.
> chore: reduce inline(always) in algorithms

- src/utils.rs
See: <https://github.com/rust-lang/hashbrown/blob/835936584e33480f6afbf1ae9be7151c1b27d595/src/raw/mod.rs#L51-L58>
> chore: likely/unlikely does not work on stable

- src/div.rs
Already checked in `algorithms::div`
> perf: remove unnecessary assertions in div_*

- src/algorithms/mod.rs
- src/algorithms/mul.rs
Turns out addmul is not that big as I thought, and inlining it provides a decent speed up, unlike division. Partially reverts https://github.com/recmo/uint/pull/374.
I also made addmul_ref test-only as the comment suggests.
> perf: re-inline always addmul

- src/algorithms/gcd/matrix.rs
- src/algorithms/gcd/mod.rs
- src/bits.rs
- src/gcd.rs
- src/modular.rs
Cases are reduced due to complex algorithms that are not really going to get any better any time soon.
- Closes #107
- Closes #141
- Closes #142
- Closes #143
- Closes #144
- Closes #145
> chore: remove TODOs about proptest cases

- CHANGELOG.md
- Cargo.toml
- src/support/scale.rs
- src/support/serde.rs
- src/support/sqlx.rs
Older versions of sqlx contain a [vulnerability](https://rustsec.org/advisories/RUSTSEC-2024-0363.html)
This vulnerability has been patched in >=0.8.1
> Bump sqlx 0.7 -> 0.8.2

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/support/diesel.rs
- src/support/mod.rs
I noticed there were some comment notes in the repo indicating a desire for diesel support. I had implemented something similar using a newtype pattern in my own project, so I figured I'd attempt to contribute it back upstream.
This PR implements the required traits for the generic uint types to work out of the box with diesel. The implementation closely matches the sqlx feature implementation in this repo. I have an example repo illustrating simple usage (schema, querying, inserting) @ https://github.com/sinasab/diesel_uint_test/.
> feat: support for diesel @ 2.2

- src/add.rs
See https://github.com/rust-lang/rust/issues/85532#issuecomment-2495119815
> perf: use bitwise operations in add/sub impls

- src/support/borsh.rs
Closes #420 
this bug will cause structs containing uints with trailing 0 bytess that are still within the fixed byte size of the integer to serialize incorrectly
don't trim, always write the exact byte size. see #421
> fix: do not trim when serializing borsch

- CHANGELOG.md
- Cargo.toml
- deny.toml
I don't see why it was pinned with `=`. This blocks automatic updates if you already have proptest 1.6 (very likely), as cargo would rather not update ruint than update it and have to downgrade proptest.
> chore(deps): unpin proptest

- CHANGELOG.md
- src/algorithms/div/knuth.rs
- src/bits.rs
- src/support/postgres.rs
Closes #428 
adds a drive-by feature to get an `Option<u8>`
> fix: some docs, and add a checked_byte

- CHANGELOG.md
- src/bytes.rs
Was tweaking https://github.com/op-rs/kona which has this repo as a dependency. Compiled kona down to mips64 which is big endian, and spotted this bug while comparing the results with little endian arch.
Minimal reproduction:
```rust
use alloy_primitives::U256;
use alloc::vec::Vec;
use alloy_rlp::Encodable;
...
let mut out = Vec::<u8>::new();
U256::from(0x12345678).encode(&mut out); // rlp encodes num
```
When we print `out` variable...
- in little endian, `[132, 18, 52, 86, 120]`, which is correct
- in big endian, `[132, 72, 44, 106, 30]`, which is wrong.
both results must be identical. 
Must swap bytes for big endian architectures, not reversing bits. 
- Unfortunately, no. We may add test suite or ci pipeline for big endian targets
> fix: swap bytes for `as_le_bytes` in big endian world

- CHANGELOG.md
- src/bits.rs
`byte_len` returns the dynamic byte length. Use `Self::BYTES` instead.
> fix: `checked_byte` bounds check and make it const

- CHANGELOG.md
- src/bytes.rs
Re-open https://github.com/recmo/uint/pull/436
Closes https://github.com/recmo/uint/issues/435
> docs: update `try_from_{b,l}e_slice` docs

- CHANGELOG.md
- src/bits.rs
- src/special.rs
Original motivation was to be able to call `byte_len()` in const context. But I added more const fn support because it was fun.
- Add const `not`
- Make `leading_zeros`, `leading_ones`, `count_ones`, `count_zeros`, `bit_len`, `byte_len`, `is_power_of_two` const
> feat: Constify leading_zeros, leading_ones, count_ones, count_zeros, bit_len, byte_len, is_power_of_two

- src/algorithms/mul_redc.rs
- src/const_for.rs
- src/log.rs
- src/modular.rs
- src/pow.rs
- src/root.rs
- allow arbitrary expressions
- allow `if` usage with any of the other variants, not just with identifiers
> chore: improve const-for usability

- .github/workflows/bench.yml
- Cargo.toml
- benches/benches/algorithms/div/reciprocal.rs
- benches/benches/algorithms/div/small.rs
- benches/benches/algorithms/gcd.rs
- benches/benches/algorithms/mul.rs
- benches/benches/prelude.rs
- ruint-bench/Cargo.toml
- ruint-bench/src/lib.rs
Some smaller benchmarks change results on every run; this is due to either:
- using `rand::rng` which is not deterministic
- so few instructions that it was benchmarking loading/storing to memory
This PR fixes both, and all benchmarks should be stable; the benchmarks still contain a lot of copies but that's out of our control: https://github.com/CodSpeedHQ/codspeed-rust/pull/98
> benches: reduce codspeed flakiness

- src/algorithms/div/mod.rs
- src/algorithms/div/small.rs
- src/algorithms/mod.rs
- src/algorithms/mul.rs
- src/div.rs
- Remove impossible panics and reduce size of possible panics (div by 0) from div dispatching code to make it more amenable for inlining
- Fix cmp for slices of different lengths; improve comments
> perf: clean up div, cmp

- benches/benches/bits.rs
- benches/benches/mod.rs
- benches/benches/prelude.rs
We don't have a bench for shift operations.
Added a bench for `overflowing_shl`, `wrapping_shl`, `overflowing_shr`, `wrapping_shr`.
> feat: add shift benchmarks

- src/macros.rs
- src/modular.rs
Rebase of https://github.com/recmo/uint/pull/458 by @Rjected.
Original description:
---
I noticed that nethermind's addmod implementation was faster than ours, and implemented differently.
I implemented a version similar to the nethermind implementation that first does an overflowing add, then calculates the remainder. If we did not overflow, reduction is done normally. Otherwise, the remainder calculation is done on a larger number of limbs.
Unfortunately we can't easily make an array of `BITS + 1` or `LIMBS + 1`, which would be much easier, maybe there's some hack we can do.
Geth's implementation seems faster (from [gas-cost-estimator](https://github.com/imapp-pl/gas-cost-estimator/blob/master/docs/report_stage_iv.md) benchmarks), impl is here: …
> perf: make add_mod faster using overflow check

- src/algorithms/div/mod.rs
- src/algorithms/mod.rs
- src/algorithms/mul.rs
- src/lib.rs
- src/mul.rs
We can roll back up the loop in add_mul_n which yields identical or better results for small lengths. For larger lengths (currently > 8) we fallback to the normal `addmul` because of the quadratic nature of the naive algorithm.
Supersedes https://github.com/recmo/uint/pull/474.
Closes #474.
> perf: roll mul_add_n

- src/cmp.rs
- src/pow.rs
- src/support/der.rs
- src/support/serde.rs
- src/support/ssz.rs
This is a minor breaking change to inference as you can see from the changed tests. This is generally acceptable if it doesn't have that big of an impact in practice.
Implement `Partial{Eq,Ord}<$int> for Uint`.
> feat: implement PartialEq, PartialOrd for primitive integers

- src/from.rs
- src/lib.rs
- src/macros.rs
Plus a fix for `as_double_words` in big endian
Same as https://github.com/recmo/uint/pull/477 for u/i 128
> perf: improve u128 conversions

- CHANGELOG.md
- src/base_convert.rs
- src/fmt.rs
- src/utils.rs
Alternative to https://github.com/recmo/uint/pull/478 by making to_base_be not allocate directly.
Closes #478.
~~Needs https://github.com/recmo/uint/pull/487 to gauge perf impact.~~
Closes https://github.com/recmo/uint/issues/294.
> feat: remove "alloc" feature requirement from base_convert/fmt

- src/cmp.rs
- src/fmt.rs
This is a very cheap check to avoid using `to_base_be` at all when the integer is small enough. It doesn't show any improvements in the benchmarks for >128 bits because the numbers are uniformly sampled, so they will always be at full bits, but it's a massive speed up as can be seen from the 64 and 128 bit benchmarks.
~~Based on #490.~~
> perf: special case small integers in fmt

- src/fmt.rs
- src/support/serde.rs
Use the stack-allocated string to format instead of using heap-allocated `format!`/`String`
> perf: almost remove alloc from serde

- src/base_convert.rs
Forgot to remove the comment in https://github.com/recmo/uint/pull/497.
Closes https://github.com/recmo/uint/issues/507.
> chore: remove opt comment

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- clippy.toml
- ruint-macro/src/lib.rs
- src/algorithms/mul_redc.rs
- src/base_convert.rs
- src/bit_arr.rs
- src/bits.rs
- src/bytes.rs
- src/fmt.rs
- src/lib.rs
- src/pow.rs
- src/string.rs
- src/support/alloy_rlp.rs
- src/support/arbitrary.rs
- src/support/fastrlp_03.rs
- src/support/fastrlp_04.rs
- src/support/postgres.rs
- src/support/scale.rs
Allows usage of `&mut` in `const fn`, `const {}` blocks, many new standard library functions in const and runtime.
1.85 was chosen for edition 2024, and it's now 3 versions old.
Unblocks https://github.com/recmo/uint/pull/449.
- Closes #504
- Closes #499
- Closes #498
- Closes #283
- Closes #282
- Closes #281
- Closes #188
- Closes #88
- I don't really know what the other features refer to, floating point is not really used
- Closes #86
> feat: bump MSRV to 1.85

- CHANGELOG.md
- src/from.rs
Adds more conversions, completing #524 , allowing f64 <-> Uint conversions without the STD feature, hopefully speeding them up as well
Again I used rust built-in code as an example as well as an article https://blog.m-ou.se/floats/
There are no benchmarks yet, I understand they need to get into the `main` branch first
> Add Uint -> f64 conversion
