.github/scripts/issue_tracker.py, .github/workflows/audit.yml, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, Changelog.md, Readme.md, build.rs, ruint-macro/Readme.md, ruint-macro/src/lib.rs, src/add.rs, src/aliases.rs, src/bytes.rs, src/const_for.rs, src/from.rs, src/lib.rs, src/string.rs, src/support/arbitrary.rs, src/support/mod.rs, src/support/proptest.rs, src/support/quickcheck.rs, src/support/rand.rs, src/support/serde.rs, src/uint_dyn/mod.rs
=> Experiment: make stable compatible

Changelog.md, cspell.json, proptest-regressions/div.txt, proptest-regressions/log.txt, proptest-regressions/mul.txt, proptest-regressions/pow.txt, src/add.rs, src/bits.rs, src/const_for.rs, src/lib.rs, src/log.rs, src/mul.rs, src/pow.rs, src/root.rs, src/special.rs, src/support/mod.rs
=> Pow and log

Changelog.md, src/from.rs, src/lib.rs, src/mul.rs
=> Widening mul

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, src/lib.rs, src/special.rs
=> Use llvm cov

Cargo.toml, Changelog.md, src/algorithms/gcd/matrix.rs, src/algorithms/mul_redc.rs, src/base_convert.rs, src/bit_arr.rs, src/bits.rs, src/from.rs, src/lib.rs, src/modular.rs, src/mul.rs, src/string.rs, src/support/num_bigint.rs, src/support/sqlx.rs
=> Small devex

src/algorithms/gcd/matrix.rs, src/algorithms/gcd/mod.rs, src/gcd.rs, src/modular.rs
=> Limit case count on slow running tests

Changelog.md, src/from.rs, src/utils.rs
https://github.com/bluealloy/revm/pull/239#discussion_r1005112221 and https://github.com/bluealloy/revm/pull/239#discussion_r1005113233
=> feat(from): `TryFrom<Uint> for usize`

Cargo.lock, Cargo.toml, Changelog.md, Readme.md, src/support/bn_rs.rs, src/support/mod.rs
=> Add bn-rs support

Changelog.md, src/bit_arr.rs
Missing `Default` implementation for `Bits` type.
Implement it.
=> feat(bit_arr): derive Default for Bits

Cargo.lock, Cargo.toml, Changelog.md, src/bit_arr.rs, src/support/rlp.rs
=> feat(support, rlp): Bits

Changelog.md, src/cmp.rs, src/support/serde.rs
Serialize/deserialize `Bits` with `serde`.
Implement `serde` support for `Bits`.
=> feat(support, serde): Bits

Changelog.md, src/support/bn_rs.rs
=> feat(support, bn-rs): Bits

Changelog.md, Readme.md, ruint-macro/Readme.md, ruint-macro/src/lib.rs, ruint-macro/tests/parse_mixed.rs, src/bit_arr.rs, src/lib.rs
Support constructing `Bits` type in `uint!` macro.
Implement it.
=> feat(macro): Bits construction

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, proptest-regressions/support/serde.txt, ruint-macro/src/lib.rs, src/from.rs, src/modular.rs, src/mul.rs, src/pow.rs, src/string.rs, src/support/serde.rs
=> Fix CI and update deps

.cargo/config.toml, Cargo.toml, src/algorithms/gcd/gcd_old.rs, src/algorithms/gcd/matrix.rs, src/const_for.rs, src/modular.rs
Fix some typos, no functional changes intended.
=> Fix some typos

CHANGELOG.md, src/from.rs
=> feat: implement TryFrom<bool>

CHANGELOG.md
=> chore: release 1.9.0

CHANGELOG.md, Cargo.toml
Updated changelog links: closes #287
=> chore: release 1.10.0

src/bits.rs
Followup to #328 
Auto-merge merged in spite of clippy issue
Fix clippy
=> Clippy for #328

CHANGELOG.md, benches/bench.rs, src/bits.rs, src/support/postgres.rs
=> fix: Shr impl

CHANGELOG.md, Cargo.toml
=> release: v1.11.1

CHANGELOG.md
Update the changelog for 1.12.0 release.
=> docs: update CHANGELOG.md for release

Cargo.toml, src/lib.rs, src/macros.rs
Should fix release issues. Tested with `cargo doc` and `cargo package`.
=> docs: fix uint! docs

CHANGELOG.md, Cargo.toml
https://docs.rs/crate/ruint/1.12.0/builds/1141804
=> docs: fix docs.rs build

src/algorithms/gcd/matrix.rs
Fix inconsistency between code and comment mentioned in #349.
Fix the comment.
=> fix: inconsistency between comment and code

src/bits.rs, src/macros.rs
Modified from intx <https://github.com/chfast/intx/blob/e0732242e36b3bb08cc8cc23445b2bee7c28b9d0/include/intx/intx.hpp#L1328>
=> perf: rewrite bit shift implementations

src/algorithms/mul.rs
Just simpler code, doesn't affect performance.
=> chore: simplify algorithms::mul*

CHANGELOG.md, Cargo.toml
Working with @prestwich to publish a new release
=> feat: release

CHANGELOG.md, src/algorithms/div/knuth.rs, src/bits.rs, src/support/postgres.rs
Resubmits #429.
Closes https://github.com/recmo/uint/issues/428
adds a drive-by feature to get an Option<u8>
=> fix: some docs, and add a checked_byte

CHANGELOG.md, Cargo.toml
Releasing along with @prestwich.
=> feat: 1.13.0

deny.toml
This lint blocks CI from being green, and it's a transitive dep we can safely ignore.
Ignore the sec advisory.
=> fix(ci): ignore paste deny lint

benches/bench.rs, benches/benches/add.rs, benches/benches/cmp.rs, benches/benches/div.rs, benches/benches/log.rs, benches/benches/mod.rs, benches/benches/modular.rs, benches/benches/mul.rs, benches/benches/pow.rs, benches/benches/root.rs, benches/prelude.rs, src/const_for.rs
Clean up common code in benchmarks and add cmp.rs
=> bench: add cmp.rs benchmarks

proptest-regressions/pow.txt, src/bits.rs, src/from.rs
Follow-up https://github.com/recmo/uint/pull/477
=> fix: gt_u64_max

src/algorithms/div/knuth.rs, src/algorithms/div/mod.rs, src/algorithms/div/reciprocal.rs, src/algorithms/div/small.rs, src/algorithms/mul_redc.rs, src/utils.rs
=> perf: elide panics in algorithms

CHANGELOG.md, Cargo.toml, README.md, src/support/ark_ff_05.rs, src/support/mod.rs
we use ark-ff v0.5, this adds the same From/Into conversion as for earlier versions
identical to v0.4, just updated versions and added new feature
=> feat: add support for ark-ff v0.5.0
